---
- name: Pull Docker Image
  hosts: all
  tasks:
    - name: Pull taskmanager_angular image
      docker_image:
        name: raj3nikhil/taskmanager_angular
        force: yes
        source: pull
    - name: Pull taskmanager_express image
      docker_image:
        name: raj3nikhil/taskmanager_express
        force: yes
        source: pull
    - name: Pull taskmanager_mongo image
      docker_image:
        name: raj3nikhil/taskmanager_mongo
        force: yes
        source: pull
