version: "3"
services:
  angular-app:
    build: ./frontend
    image: raj3nikhil/taskmanager_angular:latest
    stdin_open: true
    ports: 
      - "4200:4200"
    networks:
      - mean-app
  api-server:
    build: ./api
    image: raj3nikhil/taskmanager_express:latest
    ports:
      - "3000:3000"
    networks:
      - mean-app
    depends_on:
      - mongo
  mongo:
    image: mongo:3.6.19-xenial
    ports:
      - "28017:28017"
    networks:
      - mean-app
    volumes:
      - mongo-data:/data/db
networks:
  mean-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
